topic = "PowerMonitor" #topic name
broker = "ccrisupe0.iot.nau.edu" #broker name
load1 = "ccriiobe0.iot.nau.edu:"  #load connected to 0x40 terminals
load2 = "SOLAR CELL:"		#load connected to the 0x41 terminals
load3 = "OTHER LOAD:"		#load connected to the 0x42 terminals
cacert = "/home/mwc72/ca.crt" #path to cafile
certfile = "/home/mwc72/server.crt" #path to certfile
keyfile = "/home/mwc72/server.key" #path to keyfile
timezone = 'US/Arizona' #timezone for timestamps, consult pytz list of timezones for acceptable timezones
sleeptime = 10
