topic = "PowerMonitoring" #topic name
port = "YOUR_MQTT_PORT_NUMBER" #port to be used by mqtt
datastorage = "/SOME/PATH/TO/Data/" #path to store the local csv files, make storage directories ahead of time
broker = "YOUR BROKER NAME" #broker name or broker IP
load1 = "YOUR LOAD 1"  #load connected to 0x40 terminals
load2 = "YOUR LOAD 2"           #load connected to the 0x41 terminals
load3 = "YOUR LOAD 3"           #load connected to the 0x42 terminals
printload1 = True #boolean value to indicate if load1 is connected, if it is set to false the data will not be printed to logs
printload2 = False #boolean value to indicate if load2 is connected, if it is set to false the data will not be printed to logs
printload3 = False #boolean value to indicate if load3 is connected, if it is set to false the data will not be printed to logs
cacert = "/SOME/PATH/TO/ca.crt" #path to cafile
certfile = "/SOME/PATH/TO/server.crt" #path to certfile
keyfile = "/SOME/PATH/TO/server.key" #path to keyfile
timezone = 'US/Arizona' #timezone for timestamps, consult pytz list of timezones for acceptable timezones at https://gist.github.com/heyalexej/8bf688fd67d7199be4a1682b3eec7568
sleeptime = 10 #wait 10 seconds between publishing data
